### ISSUE TITLE
impact-crater is not in NPM

### ISSUE THREAD

**Issue by danielmahon** [impact-crater/impact-crater-core#8]
maybe there is something going on with npm right now but it wont find the package

**Comment by dylan** [comment]
Correct, impact-creater is not in NPM right now, however you will use NPM to install it, check out the README.md in the project directory to see who this works.

**Comment by danielmahon** [comment]
yea, it confused me at first as I thought you were giving 2 ways to install

**Comment by dylan** [comment]
I apologize, I'll work to improve the clarity of the docs. :+1:
